import { Routes } from "@angular/router";
import { MainComponent } from "./main/main.component";
import { RegisterViewComponent } from "./register-view/register-view.component";
import { CheckRequestsComponent } from "./request/check-requests/check-requests.component";
import { CheckInvitesComponent } from "./invites/check-invites/check-invites.component";
import { HomeComponent } from './home/home.component';
import { CreateWalletComponent } from './wallet/create-wallet/create-wallet.component';
import { RequestAccessComponent } from './request/request-access/request-access.component';
import { CreateInviteComponent } from './invites/create-invite/create-invite.component';
import { PieGraphComponent } from './graphs/pie-graph/pie-graph.component';
import { CreateExpenseComponent } from './expenses/create-expense/create-expense.component';
import { WalletStatisticsComponent } from './wallet/wallet-statistics/wallet-statistics.component';
import { CategoryStatisticsComponent } from './wallet/category-statistics/category-statistics.component';
import { UserStatisticsComponent } from './wallet/user-statistics/user-statistics.component';
import { EditWalletComponent } from './wallet/edit-wallet/edit-wallet.component';
import { WalletAdminComponent } from './admin/wallet-admin/wallet-admin.component';
import { PhotoComponent } from './photo/photo.component';
import { ShowWalletTableComponent } from './wallet/show-wallet-table/show-wallet-table.component';

export const appRoutes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'main', component: MainComponent },
  { path: 'register', component: RegisterViewComponent },
  { path: 'requestAccess', component: RequestAccessComponent },
  { path: 'checkRequests', component: CheckRequestsComponent },
  { path: 'checkInvites', component: CheckInvitesComponent },
  { path: 'createInvite', component: CreateInviteComponent },
  { path: 'createExpense', component: CreateExpenseComponent },
  { path: 'wallet', component: ShowWalletTableComponent },
  { path: 'getWalletStatistics', component: WalletStatisticsComponent },
  //TODO: вписать в путь сразу :id и как то его получать
  { path: 'catstat', component: CategoryStatisticsComponent },
  { path: 'userStatistics/:id', component: UserStatisticsComponent },
  { path: 'home', component: HomeComponent },
  { path: 'createNewWallet', component: CreateWalletComponent },
  { path: 'editWallet', component: EditWalletComponent },
  { path: 'walletAdmin', component: WalletAdminComponent },
  { path: 'photo', component: PhotoComponent },
  { path: 'graph', component: PieGraphComponent },
]